import matplotlib.pyplot as plt
import numpy as np
import scipy
import seaborn as sns
import pandas as pd
import os

NUM_STRATIFIED_FOLDS = 2
NUM_STRATIFIED_ROUNDS = 1
PARAM_SEARCH_FOLDS = 2

MIN_OBSERVATIONS_PER_SUBJECT = 40
MIN_OBSERVATIONS_PER_CLASS = 10

# Classifiers
CLASSIF_RANDOM_FOREST = 'classif-rf'
CLASSIF_XGBOOST = 'classif-xg'
CLASSIF_ORDINAL_LOGISTIC = 'classif-ord-log'
CLASSIF_ORDINAL_RANDOM_FOREST = 'classif-ord-rf'
CLASSIFIERS = [CLASSIF_RANDOM_FOREST, CLASSIF_XGBOOST, CLASSIF_ORDINAL_LOGISTIC, CLASSIF_ORDINAL_RANDOM_FOREST]

# Rankers
RANK_XGBOOST = 'ranker-xg'
RANKERS = [RANK_XGBOOST]

RUN_PARALLEL = False

DEBUG = True

RANDOM_SEED = 812
