NUM_STRATIFIED_FOLDS = 5
NUM_STRATIFIED_ROUNDS = 1
PARAM_SEARCH_FOLDS = 5

MIN_POINTS_PER_SUBJECT = 40
MIN_POINTS_PER_CLASS = 6

RANDOM_FOREST = 'random forest'
XGBOOST = 'xgboost'

DEBUG_SUBJECTS = False

RANDOM_SEED = 812
